### ISSUE TITLE
Missing information on installing Telemetry

### ISSUE THREAD

**Issue by jdsjdk** [algorand/docs#1113]
**Describe the error**

[This documentation is missing very important information on how to setup telemetry.](https://developer.algorand.org/docs/run-a-node/setup/install/#enable-telemetry)

Basically the gist of it is, that I had to open port 8080 (and not port 9243) in order to get telemetry to work.  I am using CentOS 9, so for me to open port 8080 is this:
```bash
sudo firewall-cmd --zone=public --add-port=8080/tcp --permanent
```
and for Ubuntu and Debian, you need to do this:
```bash
sudo ufw allow 8080/tcp
```

I ended up opening port 9243 _**and**_ port 8080.  Once I did that, and restarted the algorand node service, everything worked.  

**Link to the page or line**
[Please click here to see where the documentation is missing information.](https://developer.algorand.org/docs/run-a-node/setup/install/#enable-telemetry)

**Optional - The recommended fix if you have one**
Also, the documentation says 

> If the Debian package is used,

The problem is that I thought I was _except_ from having to use the this command:
`sudo -u algorand -H -E diagcfg telemetry enable` for example because I used the package manager but I was on _CentOS_.  It turns out, I needed to do it anyway.  So your documentation needs to be more general, and include the package manager install in for all package manager installations.

**Comment by barnjamin** [comment]
Thanks for the issue, will follow up with the eng team to get an updated process for enabling telemetry.

cc @algojohnlee for viz

**Comment by jdsjdk** [comment]
👍

**Comment by onetechnical** [comment]
Hi, thanks for writing. In the above, it appears you are opening up port 8080. This shouldn't affect telemetry at all, as telemetry is (optionally) writing out diagnostic logging to our logging destination. Most people do not filter egress traffic, so no further action is necessary, but if you are filtering egress, then you would have to open up port 9243.

Are you perhaps referring to the REST API? That would work after enabling ingress on port 8080.

**Comment by jdsjdk** [comment]
Hello @onetechnical.  😃 
Well unfortunately, telemetry did not work until I opened port 8080 and then restarted the process.  Once I did, everything worked.  I had already opened port 9243, and nothing worked until I opened port 8080.  So I guess you're documentation says you need to open port 8080 and port 9243.  Please let me know, and thanks again for your time.

**Comment by onetechnical** [comment]
I guess I'm not sure how you verified telemetry was working. Were you pointing to a custom telemetry destination and verifying data was getting written?

**Comment by excalq** [comment]
There's definitely opportunity to improve documentation on algod telemetry. 
I'm suspecting that the service restart is what enacted the configuration change. 

Unlike the [`/metrics` API endpoint](https://developer.algorand.org/docs/rest-apis/algod/?from_query=metrics#get-metrics), telemetry connections are outbound only, so requires no firewall changes in a default `ufw` setup.

**Comment by jdsjdk** [comment]
Well I was on CentOS @excalq.  For `firewalld` it required for me to open ports 8080 and 9243.  Once I did that, everything worked!  Anywho, now that you guys know about this, I can close the issue or you guys can if you wish.  Either way is fine by me.
:man_shrugging:
