### ISSUE TITLE
Adding an advanced topic / reference doc about encoding/decoding

### ISSUE THREAD

**Issue by fabrice102** [algorand/docs#128]
**Is your addition related to a problem? Please describe.**

For more complex workflows, it is useful to know how objects such as transactions are encoded/decoded.

See:

* https://forum.algorand.org/t/method-to-serialize-a-json-to-transaction/1259
* https://forum.algorand.org/t/javascript-frontend-communicating-with-python-backend/1728/2

**Describe the solution you'd like**

Adding an advanced topic / reference doc about encoding/decoding objects in Algorand.

This would include:

* explaining that transaction files are concatenations of msgpack-encoded transactions, with a customized version of msgpack that provides canonical encoding and omits empty fields
* explaining that addresses do not have the base32 checksum and providing a way to convert checksumed addresses from/to non-checksumed ones:
```bash
$ python3 -c "import algosdk; import base64; print(algosdk.encoding.encode_address(base64.b32decode('YESQSK5RT7WXWKCRTQN3PJZSZSMV63VDVRJAB5EBDYLXCJH5ZGTQ====')))"
YESQSK5RT7WXWKCRTQN3PJZSZSMV63VDVRJAB5EBDYLXCJH5ZGTQDBRKDE

$ python3 -c "import algosdk; import base64; print(base64.b32encode(algosdk.encoding.decode_address('YESQSK5RT7WXWKCRTQN3PJZSZSMV63VDVRJAB5EBDYLXCJH5ZGTQDBRKDE')).decode())"
YESQSK5RT7WXWKCRTQN3PJZSZSMV63VDVRJAB5EBDYLXCJH5ZGTQ====
```
* providing some background information about msgpack
* explaining that this also applies to logic sig
* showing how to encode/decode manually transactions using `msgpacktool` and the various SDK
* explaining that this allows to pass transactions around more easily
* explaining the difference between `goal clerk inspect` and `msgpacktool`
* explaining how to use msgpack to encode objects in note field

**Comment by iskysun96** [comment]
I believe this issue is addressed on this page: https://developer.algorand.org/docs/get-details/encoding/?from_query=encode#working-with-encoded-structures

Closing the issue.
