### ISSUE TITLE
Stateful contract overview - incorrect opcode

### ISSUE THREAD

**Issue by purestaketdb** [algorand/docs#189]
**Describe the error**
The opcode listed in an example is incorrect, it is labeled `app_local_get` but should be `app_global_get`

``` md
Read From State
TEAL provides calls to read global and local state values for the current smart contract. This includes reading local state To read from local or global state TEAL provides the app_local_get, app_global_get, app_local_get_ex , and app_global_get_ex opcodes. The following TEAL code reads a value from global state for the current smart contract.
byte "MyGlobalKey"
App_local_get
```

**Link to the page or line**
https://developer.algorand.org/docs/features/asc1/stateful/

**Optional - The recommended fix if you have one**
Update the example

**Optional - Supporting Screenshots**
Any accompanying screenshots that will help us identify the problem or the fix.

**Comment by ejbaran** [comment]
https://github.com/algorand/docs/pull/198

**Comment by ejbaran** [comment]
Change in staging; will soon be merged to master.
