### ISSUE TITLE
Ensure required imports within "Your First ..." pages

### ISSUE THREAD

**Issue by ryanRfox** [algorand/docs#260]
Error:
Currently the Python "Your First Transaction" code blocks do not include the required:
```python
from algosdk.future.transaction import PaymentTxn 
``` 
Therefore, a copy/paste of the code blocks will fail.

Check:
- [ ] https://developer.algorand.org/docs/build-apps/hello_world/
- [ ] https://developer.algorand.org/docs/features/asc1/stateful/hello_world/

Fix:
- [ ] Review the pages above.
- [ ] Add all imports
- [ ] Test the code blocks for each SDK

**Comment by iskysun96** [comment]
outdated issue. Closing.
