### ISSUE TITLE
Two errors in examples/smart_contracts/v2/javascript/statefulSmartContracts.js

### ISSUE THREAD

**Issue by purestaketdb** [algorand/docs#261]
**Describe the error**
Two minor errors prevent the script from running as-is

1. In main() the API server is `algodServer` but the global defined variable is actually named `algodAddress`

2. In main() a date is created as a UTC string, then cast back to a Date object. Later, the date is used in `Buffer.from()` which expects only a string and throws a TypeError. 

```JS
err TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type number
    at Function.from (buffer.js:305:9)
    at Function.from (buffer.js:292:21)
    at main (/Users/tdb/Documents/GitHub/sdk-samples/javascript/app-setup.js:517:40)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Link to the page or line**
Link to the page and line/s if applicable either in the markdown version or on the site itself.

https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/statefulSmartContracts.js

1. line 8
2. line 550-553

**Optional - The recommended fix if you have one**
If you know what the change should be, tell us here.

1. Change `algodAddress` to `algodServer`
2. drop the wrapping `new Date()` leaving only `new Date().toUTCString();`

**Optional - Supporting Screenshots**
Any accompanying screenshots that will help us identify the problem or the fix.

**Comment by iskysun96** [comment]
Fixed. Closing issue.
