### ISSUE TITLE
Example Usage of PaymentTxn in "Your First Transaction" is Outdated

### ISSUE THREAD

**Issue by hsiuhsiu** [algorand/docs#293]
**Describe the error**
The constructor of the class `algosdk.transaction.PaymentTxn` now take transaction parameters directly rather than with a wrapper. So the line 
```
unsigned_txn = PaymentTxn(my_address, params, receiver, 1000000, None, note)
```
is not working.

**Link to the page or line**
https://developer.algorand.org/docs/build-apps/hello_world/

**Optional - The recommended fix if you have one**
The line can be changed to
```
unsigned_txn = transaction.PaymentTxn(
    sender=my_address,
    fee=params.fee,
    first=params.first,
    last=params.last,
    gh=params.gh,
    receiver=receiver,
    amt=1000000,
    note=note)
```

**Comment by ejbaran** [comment]
These examples have been update to v2 now and this issue should now be resolved. Thank you!
