### ISSUE TITLE
~/node/data references

### ISSUE THREAD

**Issue by rfustino** [algorand/docs#316]
This page needs fixing https://developer.algorand.org/docs/reference/sdks/
~/node/data - debain install runs into problems with ~/node/data 

see how we do it on this page

https://developer.algorand.org/docs/build-apps/setup/#3-run-your-own-node

We use ~/node/data all over the site and should be updated

**Comment by JasonWeathersby** [comment]
Agreed Russ

**Comment by iskysun96** [comment]
Website updated. Will close this.
