### ISSUE TITLE
No call_app() method

### ISSUE THREAD

**Issue by avislash** [algorand/docs#341]
**Describe the error**
The "Call with Arguments" section of the Python SDK ASC tutorial references a method called **call_app** that doesn't exist.
**Link to the page or line**
https://developer.algorand.org/docs/features/asc1/stateful/sdks/#call-with-arguments

**Optional - The recommended fix if you have one**
Either remove this line from the Python Snippet or add a definition for the function. 

**Optional - Supporting Screenshots**
Any accompanying screenshots that will help us identify the problem or the fix.

**Comment by ejbaran** [comment]
https://github.com/algorand/docs/pull/344
