### ISSUE TITLE
Missing one transaction type in the "transaction type" documentation

### ISSUE THREAD

**Issue by bofeng** [algorand/docs#347]
**Describe the error**

In the documentation page here:
https://developer.algorand.org/docs/features/transactions/#transaction-types
It says:
> There are five transaction types in the Algorand Protocol: 1) Payment, 2) Key Registration, 3) Asset Configuration, 4) Asset Freeze, 5) Asset Transfer.

But if you read the smart contract section, clearly there is an another "Application Call" type, and in the "transaction reference" page (check the link below), it listed the "application type", its value is "appl":
https://developer.algorand.org/docs/reference/transactions/#application-call-transaction

Plus, in the source code it has the "appl" transaction type too:
https://github.com/algorand/go-algorand/blob/master/protocol/txntype.go#L42

So I am thinking this page https://developer.algorand.org/docs/features/transactions/#transaction-types
 is most likely outdated and missing the "appl" transaction type.

**Comment by iskysun96** [comment]
issue fixed. Closing. Thank you!
