### ISSUE TITLE
Node Configuration Settings Missing Options

### ISSUE THREAD

**Issue by Blackglade** [algorand/docs#380]
**Is your addition related to a problem? Please describe.**
The Node Configuration Settings Page ( https://developer.algorand.org/docs/reference/node/config/)  is missing options that are found within the config file. Specifically, these options:

```json
{
    "AccountsRebuildSynchronousMode": 1,
    "CatchpointTracking": 0,
    "EnableCatchupFromArchiveServers": false,
    "LedgerSynchronousMode": 2,
    "MaxCatchpointDownloadDuration": 7200000000000,
    "MinCatchpointFileDownloadBytesPerSecond": 20480,
    "NetworkMessageTraceServer": "",
    "OptimizeAccountsDatabaseOnStartup": false,
    "VerifiedTranscationsCacheSize": 30000
}
```

**Describe the solution you'd like**
I would like this to get resolved as soon as possible.

**Comment by iskysun96** [comment]
resolved.
