### ISSUE TITLE
Incorrect API Spec for Algod

### ISSUE THREAD

**Issue by Blackglade** [algorand/docs#428]
**Describe the error**
The developer documentation for the responses when querying /v2/blocks/{round} are incorrect. The docs state that when a query is made to a block that doesn't exist yet, an `ErrorResponse` is returned with a `404` code with the message: `None existing block`. Instead when querying for a block that's not in the blockchain, say like block 20000000 on mainnet, I get a 500 with the following message:

```
{"message":"ledger does not have entry 20000000 (latest 14441194, committed **14441194)"}
```

Would like some clarification on this on whether the docs are incorrect or the implemented behavior is incorrect,

**Link to the page or line**
https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#get-v2blocksround

**Comment by iskysun96** [comment]
There is an issue on this. Will update the doc once this issue is resolved. https://github.com/algorand/go-algorand/issues/3835
