### ISSUE TITLE
Links with `name=` don't function well

### ISSUE THREAD

**Issue by Fluffycup** [algorand/docs#441]
**Describe the error**
So when trying to refer to the reference docs for specific classes and their attributes the markdown pages, then desired field to see is hidden by the algorand banner.

**Link to the page or line**
https://developer.algorand.org/docs/features/transactions/#freeze-an-asset
The freeze manager link will take you to the freezeaddr field seen in the first screenshot below, but it will get hidden in the banner via the gif

**Optional - The recommended fix if you have one**
Right now I'd probably say just link to the page sections, those work correctly, and then adjust the wording before each link to explain more clearly how to look for that

**Optional - Supporting Screenshots**
![CleanShot 2021-06-23 at 10 56 35](https://user-images.githubusercontent.com/11368049/123120112-0f87f400-d412-11eb-9891-0107de13226f.png)

![CleanShot 2021-06-23 at 11 00 06](https://user-images.githubusercontent.com/11368049/123120419-4bbb5480-d412-11eb-96dc-d48d290ed840.gif)

**Comment by iskysun96** [comment]
Seems to be working fine now. Closing the issue
