### ISSUE TITLE
Rust SDK Icon incorrect

### ISSUE THREAD

**Issue by barnjamin** [algorand/docs#564]
**Describe the error**
On the ecosystem page the icon for the Rust sdk shows the Rust game icon not something related to the language

![image](https://user-images.githubusercontent.com/520236/135298937-92a55e83-ddd2-4277-b989-996c3f44d597.png)

https://en.wikipedia.org/wiki/Rust_(video_game)

vs

https://en.wikipedia.org/wiki/Rust_(programming_language)

**Comment by ejbaran** [comment]
Thank you! Resolved.
