### ISSUE TITLE
Typo on algorealm page

### ISSUE THREAD

**Issue by iskysun96** [algorand/docs#630]
**Describe the error**
There is a typo:
“Delegating...the corresponding donation is grater than the existing one.” <-- grater

**Link to the page or line**
Link to the page and line/s if applicable either in the markdown version or on the site itself.
https://developer.algorand.org/solutions/algorealm-nft-royalty-game/#algorealm

**Optional - The recommended fix if you have one**
If you know what the change should be, tell us here.
change grater -> greater

**Optional - Supporting Screenshots**
Any accompanying screenshots that will help us identify the problem or the fix.

**Comment by barnjamin** [comment]
@cusma
