### ISSUE TITLE
Fix typo and clarify reason for payment transaction that funds smart contract

### ISSUE THREAD

**Issue by NeoDaoist** [algorand/docs#635]
**Type:** Fixing Errors or Inaccuracies – Typo

**Describe the error**
Typo in **Setup the Auction** section of **Build with Python** page — but only on `master` branch, not on `staging` branch

**Link to the page or line**
https://developer.algorand.org/docs/get-started/dapps/pyteal/#setup-the-auction
https://github.com/algorand/docs/blob/master/docs/get-started/dapps/pyteal.md?plain=1#L244

> one payment transaction to fund the smart contract with **a algos** to cover minimum balance requirements and transaction fees,

**Optional - The recommended fix if you have one**
> one payment transaction to fund the smart contract with **a small amount of algos** to cover minimum balance requirements and transaction fees,

**Optional - Supporting Screenshots**
N/A

**Comment by barnjamin** [comment]
Thanks! I've set this to be closed when staging is merged with master
