### ISSUE TITLE
Fast Catchup section should mention that its not applicable for Archival nodes

### ISSUE THREAD

**Issue by AncyThomas91** [algorand/docs#640]
**The current state**
https://developer.algorand.org/docs/run-a-node/setup/install/#sync-node-network-using-fast-catchup

**The proposed state**
A info or warning box mentioning that Fast Catchup cannot be done on Archival nodes

**Provide any additional context**
Add any other context or screenshots about the proposed update here.

**Comment by iskysun96** [comment]
warning box added. Closing the issue now
