### ISSUE TITLE
smart contract example of javascript deprecated

### ISSUE THREAD

**Issue by PabloLION** [algorand/docs#682]
## Description
It seems that here in these lines are some problems

### Snippet 1
https://github.com/algorand/docs/blob/04e80a184902733f7854e090aa19d36ef96d3f18/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L70-L74

- Definition of `args`, these three are contradict to each other. 
  - This same problem also appreas in `AccountDelegation.js` and `ContractAccount.js` in same folder.
  - L70, it's a `string[]`, as the comment says `args = ["<my string>"];` 
  - L73, it's a `number[][]`. 
  - L74, it's a `Uint8Array[]` to be called by `algosdk.makeLogicSig`. 
  - My JS engine cannot run it either, TS engine can either solve this(after change is to `ts`).

- L74: `algosdk.makeLogicSig` is deprecated by `@deprecated Use new LogicSigAccount(...) instead` from 
 https://github.com/algorand/js-algorand-sdk/blob/462a9b8a3b217de606e3bd3d450b36671a6b7897/src/logicsig.ts#L351

### Snippet 2

https://github.com/algorand/docs/blob/04e80a184902733f7854e090aa19d36ef96d3f18/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L128-L135

- algosdk.modelsv2.DryrunSource
  ```
  Expected 4 arguments, but got 3.ts(2554)
  types.d.ts(702, 79): An argument for 'appIndex' was not provided.
  ```
  I checked the latest JS-SDK repo and it does expect 4 args.
  https://github.com/algorand/js-algorand-sdk/blob/a80a1e6d683aef12bf72431c6842530b1bb26235/src/client/v2/algod/models/types.ts#L1127-L1155

- `algosdk.modelsv2.DryrunRequest`
  The required object is very different than the passed one.

## P.S.

**Link to the page or line: see above**
**I don't know how to fix**
I want to know which of these are designed so, or a problem?
Thanks.

**Comment by iskysun96** [comment]
@rfustino Can you look into this?
