### ISSUE TITLE
Removing references to Algorand Studio / Algorand VS Code extension - indicate they are out-of-date

### ISSUE THREAD

**Issue by fabrice102** [algorand/docs#693]
**The current state**

Pages like https://developer.algorand.org/docs/sdks/java/ recommend the use of Algorand Studio / Algorand VS Code extension.

Unfortunately both these tools have not been updated for a very long time.
In particular:
* They don't support fast catchup and instead use a very old method of fast syncing (downloading the data folder in a compressed way). Not only is this method more dangerous from a security point of view (what happens if the endpoint gets corrupted) but also the endpoint used only provide a data folder from before https://testnet.algoexplorer.io/block/12321367, that is almost a year ago. This means catchup takes a huge amount of time.
* They don't support even TEAL v2.

**The proposed state**

Remove all references to Algorand Studio / Algorand VS Code and promote AlgoDEA that is up to date.

**Comment by JasonWeathersby** [comment]
These should be removed from those pages
