### ISSUE TITLE
Use ALGORAND_MIN_TX_FEE constants instead of hard coded 1,000 microAlgos for min fees

### ISSUE THREAD

**Issue by fabrice102** [algorand/docs#704]
**The current state**

In JS, when using a flat fee, the value 1000 microAlgos is hardcoded:
https://developer.algorand.org/docs/sdks/javascript/?from_query=JS%20first%20#build-first-transaction

**The proposed state**

Replace the hardcoded 1000 microAlgos with `algosdk.ALGORAND_MIN_TX_FEE`.
Similar changes for other SDKs if appropriate.

**Comment by iskysun96** [comment]
@fabrice102 the change is applied. Please close this issue.
