### ISSUE TITLE
Build with PyTeal auction example does not read pythonically

### ISSUE THREAD

**Issue by BenDavidAaron** [algorand/docs#714]
**Is your addition related to a problem? Please describe.**
The auction example in the Build with PyTeal docs foregoes many of the naming and capitalization conventions that are de facto standards in the python ecosystem. 
These include using camelCase for variable and function names (which are conventionally snake_case), and using `assert` to check for errors instead of a conditional followed by raising the appropriate exception. 
The code samples read like they were translated from Go, and it's not intuitive to read as a Python developer. 

**Describe the solution you'd like**
I would like to re-write the python example code in this module to follow the [Google Python Styleguide](https://google.github.io/styleguide/pyguide.html#24-exceptions).

**Describe alternatives you've considered**
I guess I could switch to working in Go.

**Additional context**
Onboarding new developers to the algorand ecosystem will be a boon for the ecosystem, this suggested change will reduce the friction that your average Python developer will experience when adopting PyTeal and Algorand. I'm happy to make the changes myself and submit a PR.

**Comment by iskysun96** [comment]
Hello @BenDavidAaron 

Have you submitted a PR on this issue?

**Comment by BenDavidAaron** [comment]
I have not, got distracted by some other projects. I can try to revisit it when I have bandwidth. Should probably close this for now.
