### ISSUE TITLE
awesome_pages outdated

### ISSUE THREAD

**Issue by PabloLION** [algorand/docs#728]
Also after `pip3 install -r requirements.txt` the awesome-page is throwing some error. Please check.(should I create a new issue?)

```bash
  File "/opt/homebrew/lib/python3.10/site-packages/mkdocs_awesome_pages_plugin/plugin.py", line 9, in <module>
    from .meta import DuplicateRestItemError, MetaNavRestItem, RestItemList
  File "/opt/homebrew/lib/python3.10/site-packages/mkdocs_awesome_pages_plugin/meta.py", line 78, in <module>
    class RestItemList(collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```

_Originally posted by @PabloLION in https://github.com/algorand/docs/issues/725#issuecomment-1030447207_

**Comment by barnjamin** [comment]
I expect this is an issue between py 3.10 and the version of awesome pages, if you can find one that works and PR it ill test against it on the version I'm using

**Comment by PabloLION** [comment]
I agree with your expectation. I was using py3.9 before and there was no such Exception. If you didn't change anything, maybe add a "not support py3.10" in https://github.com/algorand/docs/blob/staging/CONTRIBUTING.md

**Comment by nullun** [comment]
@PabloLION when I ran into this error I'm fairly sure I just updated all three requirements to their latest version at the time and its working fine (Python 3.10.1)

```
mkdocs-material==8.1.7
mkdocs-awesome-pages-plugin==2.6.1
importlib-metadata==4.10.1
```

**Comment by PabloLION** [comment]
@nullun  Maybe you can make a PR? I'll test there
