### ISSUE TITLE
Sort within group on ecosystem page: https://developer.algorand.org/ecosystem-projects/

### ISSUE THREAD

**Issue by rfustino** [algorand/docs#738]
**The current state**
It is getting harder to "read" the page  with so many new entries now that we are accepting new submissions thru the portal. They are not alphabetical within each group. There is not an easy way to rearrange them when entering and/or displaying. Group headers could be sorted as well. 

**The proposed state**
Automatically sort alphabetical in each category.  Snapshot attached showing order is the way they were entered. Sort categories as well would make sense too. 

**Provide any additional context**
Maybe add a sort by field w order number within group when entering the new tools here, as well as an order number on the category list headers.  https://developer.algorand.org/cp/community/ecosystemprojectcategory/ 
 
![applications](https://user-images.githubusercontent.com/4959925/153088010-6de8bd78-adea-4dd0-bc64-2b04ed4408a9.png)

**Comment by jsgranados** [comment]
This was completed to what seems to be a long time ago. Closing.
