### ISSUE TITLE
Sending a Unit8Array signedTxn.blob to a Backend

### ISSUE THREAD

**Issue by matamicen** [algorand/docs#742]
**The current state**
I don't find this clarification.

**The proposed state**
Explain that a signedTxn.blob in the frontend is in a Unit8Array format and has to be converted to a string before sending to the backend in an API.

**Provide any additional context**
Sometimes you need the user sign the Tx and send that Tx to the chain in the backend.

**Comment by barnjamin** [comment]
https://developer.algorand.org/docs/get-details/encoding/#transaction this should cover it but please PR if you would add anything

**Comment by iskysun96** [comment]
closing this issue for now. If further fix is needed, please PR like @barnjamin said!
