### ISSUE TITLE
`AssetCloseTo` shouldn't be in Asset Clawback Transaction Reference

### ISSUE THREAD

**Issue by canbolukbas** [algorand/docs#800]
**Describe the error**
`Asset Clawback Transaction` shouldn't have the `AssetCloseTo` field in the Transaction Reference. It is contradicting with the implementation in `go-algorand`. It also contradicts with the spec of Asset Transaction Semantics:

> If the asset source field is non-zero, the transaction must be issued by the asset’s clawback account, and this transaction can neither allocate nor close out holdings of an asset (i.e., the asset close-to field must not be specified, and the source account must already have allocated space to store holdings of the asset in question).

**Link to the page or line**
Asset Clawback Transaction Reference:
https://github.com/algorand/docs/blob/staging/docs/get-details/transactions/transactions.md#asset-clawback-transaction
Related Implementation in `go-algorand`: 
https://github.com/algorand/go-algorand/blob/e1ae88839dd5dba4a3900940ba8fd64d7b982f2d/ledger/apply/asset.go#L335
Spec of Asset Transaction Semantics:
https://github.com/algorandfoundation/specs/blob/master/dev/ledger.md#asset-transaction-semantics

**Optional - The recommended fix if you have one**
Deleting `AssetCloseTo` row from Asset Clawback Transaction reference.

**Optional - Supporting Screenshots**
![Screen Shot 2022-04-06 at 13 54 08](https://user-images.githubusercontent.com/39600723/162406441-73314b8b-3143-442c-b4c0-aaf1ce8f23be.png)

**Comment by nullun** [comment]
Great catch! Thank you. This has been PR'ed in #801
