### ISSUE TITLE
Link Wallet Connect Example back to Github and developer docs

### ISSUE THREAD

**Issue by fabrice102** [algorand/docs#859]
**The current state**

https://github.com/algorand/walletconnect-example-dapp does not provide link back to its github repo (https://github.com/algorand/walletconnect-example-dapp) nor to the developer documentation.

**The proposed state**

Adding those links.

**Provide any additional context**

https://forum.algorand.org/t/algorand-walletconnect-demo-source/7457/2?u=fabrice

**Comment by iskysun96** [comment]
@fabrice102 

Can you elaborate what the problem is? You put the same link under "The current state"

**Comment by iskysun96** [comment]
@fabrice102 

If you are talking about this page on the doc (https://developer.algorand.org/docs/get-details/walletconnect/?from_query=wallet%20connect#create-publication-overlay), the github is already linked.

**Comment by fabrice102** [comment]
Sorry it was unclear: I meant linking in the opposite direction.
This means changing https://github.com/algorand/walletconnect-example-dapp to include a link back to https://developer.algorand.org/docs/get-details/walletconnect/
and https://algorand.github.io/walletconnect-example-dapp/ to link back to https://github.com/algorand/walletconnect-example-dapp and https://developer.algorand.org/docs/get-details/walletconnect/
