### ISSUE TITLE
Update links to JavaScript, Java, Python and go SDKs

### ISSUE THREAD

**Issue by 0xpranjal** [algorand/docs#920]
**Describe the error**
The current links referencing development using the four SDKs returns a 404 error. Attaching screenshot below:

<img width="918" alt="Screenshot 2022-10-12 at 4 25 57 PM" src="https://user-images.githubusercontent.com/50989807/195325016-d7617a9b-5f64-43f5-bde6-41061cd30be9.png">

**Link to the page or line**
https://developer.algorand.org/docs/archive/build-apps/setup/#software-development-kits-sdk

**Supporting Screenshots**

<img width="1074" alt="Screenshot 2022-10-12 at 4 27 32 PM" src="https://user-images.githubusercontent.com/50989807/195325341-a4be0953-a4b0-49af-86fe-937535e996f2.png">

**Comment by nullun** [comment]
Hey @0xpranjal, thanks for creating the issue, however we've chosen not to update the pages in the archive section as they've already been superseded. We'll look at trying to get a banner/message at the top of these pages to indicate the links may not work.
