### ISSUE TITLE
Transaction page needs some tweaks

### ISSUE THREAD

**Issue by rfustino** [algorand/docs#987]
[Transaction Page](https://developer.algorand.org/docs/get-details/transactions) needs some minor updates
Boxes need to be added to list

Boxes - To pass as many boxes as needed. Each entry in the box array allows access to 1kb of data. 

![Boxes need to be added to list](https://user-images.githubusercontent.com/4959925/213034371-7732a092-98cc-4c59-a172-777e0ddf7f21.png)
Should be 7 not 6
![Should be 7 not 6](https://user-images.githubusercontent.com/4959925/213034375-5dded658-7eaf-443c-8913-b18d645f4bf9.png)
Bad Link on Guide 404
![Bad Link on Guide](https://user-images.githubusercontent.com/4959925/213034376-abceea96-2fb5-4292-ab59-0c9e72078fad.png)

**Comment by cusma** [comment]
Box information should be added also to Application Call in [Transaction Reference page](https://developer.algorand.org/docs/get-details/transactions/transactions/#application-call-transaction).
